/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projecteular.Questions;

/**
 *
 * @author Tolga
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 * find the sum of the even-valued terms.
 */
public class ProjectEular_Q2_Even_Fibonacci_Numbers {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        System.out.println(sumEvenFibonacciNumbers(4000000));
    }
    
    // Fibonacci : 
    public static long getFibonacci(int count, long calc) {
        if(count > 1)
        {
            return getFibonacci(count-1, calc) + getFibonacci(count-2, calc);
        }
        else
            return 1;
    }
    
    // Fibonacci Even Valued Terms Summation : 
    public static long sumEvenFibonacciNumbers(long max) {
        long first   = 1;
        long second  = 2;
        long sum     = 0;
        long temp;
        
        while(first < max) {
            if(first % 2 == 0)
                sum += first;
            
            temp = second;
            second = first + temp;
            first  = temp;
        }
        
        return sum;
    }
    
}
